name: Scala CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "zulu"
          cache: sbt
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Restore cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.ivy2/local
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/*.sbt', 'project/*.scala') }}
          restore-keys: |
            ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/*.sbt', 'project/*.scala') }}
            ${{ runner.os }}-sbt-
      - name: Restore cache node
        uses: actions/cache@v4
        with:
          path: |
            modules/client/node_modules
            modules/client/scalablytyped/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('modules/client/package.json', 'modules/client/scalabytyped/package.json') }}

      - name: Compile Scala code
        run: ./scripts/setup.sh
