name: Scala CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "zulu"
          cache: sbt
      - name: Install sbt
        uses: sbt/setup-sbt@v1
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            modules/client/node_modules
            modules/client/scalablytyped/node_modules
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/**', 'modules/client/node_modules/*.json', 'modules/client/scalabytyped/node_modules/*.json') }}

      - name: Compile Scala code
        run: ./scripts/setup.sh
